# Blueprint specification: https://render.com/docs/blueprint-spec

services:
  - type: pserv
    name: mydatabase
    region: frankfurt
    plan: free

  - type: web
    name: mywebapp
    region: frankfurt
    plan: free
    env: node

    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromService:
          name: mydatabase
          property: connectionString
